version: '2'
services:
  db:
    image: my-app-example-db:ltst
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=my_app_example
    ports:
    - 5432:5432
    container_name: my-app-example-db-container
  server:
    image: my-app-example-server:ltst
    command:
    - --gateway.endpoint=/
    - --database.address=db
    - --database.port=5432
    - --database.name=my_app_example
    - --database.user=postgres
    - --database.password=postgres
    - --database.ssl=disable
    - --gateway.swaggerFile=tmp/www/swagger
    ports:
    - 8080:8080
    container_name: my-app-example-server-container
    links:
    - db
  swagger:
    image: swaggerapi/swagger-ui
    environment:
    - API_URL=http://localhost:8080/swagger/
    ports:
    - 8090:8080
    container_name: my-app-swagger-container
    links:
    - server