// Code generated by protoc-gen-go. DO NOT EDIT.
// source: my-app-example/pkg/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	my-app-example/pkg/pb/service.proto

It has these top-level messages:
	VersionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyAppExample service

type MyAppExampleClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type myAppExampleClient struct {
	cc *grpc.ClientConn
}

func NewMyAppExampleClient(cc *grpc.ClientConn) MyAppExampleClient {
	return &myAppExampleClient{cc}
}

func (c *myAppExampleClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/service.MyAppExample/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyAppExample service

type MyAppExampleServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
}

func RegisterMyAppExampleServer(s *grpc.Server, srv MyAppExampleServer) {
	s.RegisterService(&_MyAppExample_serviceDesc, srv)
}

func _MyAppExample_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAppExampleServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.MyAppExample/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAppExampleServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyAppExample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.MyAppExample",
	HandlerType: (*MyAppExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _MyAppExample_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my-app-example/pkg/pb/service.proto",
}

func init() { proto.RegisterFile("my-app-example/pkg/pb/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x59, 0x0f, 0xae, 0x06, 0x41, 0xe9, 0x41, 0x4a, 0xf5, 0x20, 0xeb, 0x45, 0xd0, 0x26,
	0xa0, 0x37, 0xf7, 0xa4, 0xb0, 0x78, 0x12, 0x64, 0x0f, 0x1e, 0x3c, 0x99, 0xac, 0xd3, 0x18, 0x6c,
	0x33, 0x43, 0x93, 0xad, 0xdb, 0xab, 0xaf, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x74, 0x93, 0x4a,
	0xd1, 0xbd, 0x65, 0x66, 0xfe, 0x1f, 0xf0, 0x0b, 0x3b, 0xad, 0xda, 0x5c, 0x12, 0xe5, 0xb0, 0x92,
	0x15, 0x95, 0x20, 0xe8, 0x4d, 0x0b, 0x52, 0xc2, 0x41, 0xdd, 0x98, 0x05, 0x70, 0xaa, 0xd1, 0x63,
	0x32, 0x8e, 0x63, 0x76, 0xa4, 0x11, 0x75, 0xa7, 0xea, 0xd6, 0x6a, 0x59, 0x08, 0xa8, 0xc8, 0xb7,
	0x41, 0x95, 0x1d, 0xc7, 0xa3, 0x24, 0x23, 0xa4, 0xb5, 0xe8, 0xa5, 0x37, 0x68, 0x5d, 0xbc, 0x4e,
	0xb5, 0xf1, 0xaf, 0x4b, 0xc5, 0x17, 0x58, 0x89, 0xb2, 0x2d, 0x7c, 0xc8, 0x58, 0xe4, 0x1a, 0x6c,
	0xde, 0xc8, 0xd2, 0xbc, 0x48, 0x0f, 0xe2, 0xdf, 0x23, 0x9a, 0x2f, 0x06, 0x62, 0xf7, 0x2e, 0xb5,
	0x86, 0x5a, 0x20, 0xad, 0xe3, 0x37, 0x54, 0x5d, 0x0f, 0xaa, 0x8c, 0x2d, 0x50, 0x95, 0xb8, 0x42,
	0x02, 0x3b, 0xac, 0xd4, 0x58, 0x57, 0xbf, 0x11, 0xdd, 0x10, 0xbc, 0x93, 0x73, 0xb6, 0xff, 0x08,
	0xb5, 0x33, 0x68, 0xe7, 0xe0, 0x08, 0xad, 0x83, 0x24, 0x65, 0xe3, 0x26, 0xac, 0xd2, 0xd1, 0xc9,
	0xe8, 0x6c, 0x77, 0xde, 0x8f, 0x97, 0xcf, 0x6c, 0xef, 0xbe, 0xbd, 0x21, 0x9a, 0x05, 0x78, 0xc9,
	0x03, 0x63, 0x77, 0xe0, 0xa3, 0x3f, 0x39, 0xe4, 0x01, 0x08, 0xef, 0x69, 0xf1, 0x59, 0x47, 0x2b,
	0x4b, 0x79, 0x4f, 0xf7, 0x4f, 0xd3, 0xe4, 0xe0, 0xe3, 0xeb, 0xfb, 0x73, 0x8b, 0x25, 0x3b, 0x22,
	0x36, 0xdc, 0x66, 0x4f, 0xe9, 0xc6, 0x0f, 0x9a, 0x92, 0x52, 0xdb, 0xeb, 0xdc, 0xab, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x91, 0x48, 0x6d, 0x4a, 0xc3, 0x01, 0x00, 0x00,
}
